server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: github-bot-route
          uri: http://localhost:8085
          predicates:
            - Path=/pull-request/**, /github/**
        - id: test-runner-route
          uri: http://localhost:8084
          predicates:
            - Path=/test/**
        - id: orchestrator-route
          uri: http://localhost:8083
          predicates:
            - Path=/orchestrator/**

logging:
  level:
    com.gitoracle.apigateway: INFO
    org.springframework.cloud.gateway: INFO
